FROM debian:bullseye

RUN apt-get update && apt-get install -y \
    iproute2 \
    iputils-ping \
    net-tools \
    iptables \
    vlan \
    bridge-utils \
    tcpdump \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Enable 8021q VLAN module support
RUN echo "8021q" >> /etc/modules

CMD ["sleep", "infinity"]
